import imgApp from "@/assets/images/app-icon-1755503038459.png";
import { AndroidMotionEventButton } from "@yume-chan/scrcpy";
export const products = [
  {
    id: 1,
    name: "Galaxy A6",
    description:
      "Original ROM Phù hợp chạy App, chạy Trao đổi tương tác, Golike,...",
    available: 262,
    sold: "999+",
    price: "15.000đ/ngày",
    rating: 4.8,
    specs: {
      resolution: "720×1480 Pixels",
      cpu: "Exynos 7870 Octa",
      ram: "3GB RAM",
      storage: "32GB Storage",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "94%",
  },
  {
    id: 2,
    name: "Samsung Galaxy Note 8",
    description:
      "Original ROM Phù hợp chạy App, chạy Trao đổi tương tác, Golike,...",
    available: 7,
    sold: "999+",
    price: "25.000đ/ngày",
    rating: 4.9,
    specs: {
      resolution: "1440 × 2960 pixels",
      cpu: "Exynos 8895 Octa",
      ram: "6GB RAM",
      storage: "64GB Storage",
      android: "Android 9",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "94%",
  },
  {
    id: 3,
    name: "Samsung Galaxy Note 8 (Pro)",
    description: "Change Device/ BackUp App / Restore App / Automation App",
    available: 6,
    sold: "999+",
    price: "30.000đ/ngày",
    rating: 4.7,
    specs: {
      resolution: "1440 × 2960 pixels",
      cpu: "Exynos 8895 Octa",
      ram: "6GB RAM",
      storage: "64GB Storage",
      android: "Android 13",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "94%",
  },
  {
    id: 4,
    name: "Samsung Galaxy Note 8 (Rooted)",
    description: "Lineage OS + Magisk",
    available: 0,
    sold: "999+",
    price: "35.000đ/ngày",
    rating: 4.6,
    specs: {
      resolution: "1440 × 2960 pixels",
      cpu: "Exynos 8895 Octa",
      ram: "6GB RAM",
      storage: "64GB Storage",
      android: "Android 10",
      rooted: "ROM : Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "94%",
    outOfStock: true,
  },
  {
    id: 5,
    name: "Galaxy S9",
    description: "Stable ROM, phù hợp automation và testing",
    available: 45,
    sold: "120",
    price: "18.000đ/ngày",
    rating: 4.5,
    specs: {
      resolution: "1440×2960",
      cpu: "Exynos 9810",
      ram: "4GB RAM",
      storage: "64GB",
      android: "Android 9",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "80%",
  },
  {
    id: 6,
    name: "Galaxy S10",
    description: "Good performance for app interaction tests",
    available: 30,
    sold: "300",
    price: "22.000đ/ngày",
    rating: 4.6,
    specs: {
      resolution: "1440×3040",
      cpu: "Exynos 9820",
      ram: "8GB RAM",
      storage: "128GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "88%",
  },
  {
    id: 7,
    name: "Galaxy A10",
    description: "Nhẹ, tiết kiệm tài nguyên cho testing đơn giản",
    available: 180,
    sold: "50",
    price: "10.000đ/ngày",
    rating: 4.1,
    specs: {
      resolution: "720×1520",
      cpu: "MediaTek",
      ram: "2GB RAM",
      storage: "32GB",
      android: "Android 9",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "70%",
  },
  {
    id: 8,
    name: "Galaxy A20",
    description: "Cân bằng giữa hiệu năng và giá thuê",
    available: 95,
    sold: "220",
    price: "12.000đ/ngày",
    rating: 4.2,
    specs: {
      resolution: "720×1560",
      cpu: "Exynos/MediaTek",
      ram: "3GB RAM",
      storage: "32GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "60%",
  },
  {
    id: 9,
    name: "Galaxy M20",
    description: "Pin khỏe, phù hợp test dài hạn",
    available: 40,
    sold: "150",
    price: "14.000đ/ngày",
    rating: 4.3,
    specs: {
      resolution: "1080×2340",
      cpu: "Exynos",
      ram: "4GB RAM",
      storage: "64GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "75%",
  },
  {
    id: 10,
    name: "Galaxy M30",
    description: "Hiệu năng tốt cho automation nặng",
    available: 22,
    sold: "80",
    price: "20.000đ/ngày",
    rating: 4.4,
    specs: {
      resolution: "1080×2340",
      cpu: "Exynos",
      ram: "6GB RAM",
      storage: "64GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "82%",
  },
  {
    id: 11,
    name: "Galaxy Note 9",
    description: "S Pen hỗ trợ các thao tác chuyên sâu",
    available: 10,
    sold: "200",
    price: "28.000đ/ngày",
    rating: 4.6,
    specs: {
      resolution: "1440×2960",
      cpu: "Exynos 9810",
      ram: "6GB RAM",
      storage: "128GB",
      android: "Android 9",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "90%",
  },
  {
    id: 12,
    name: "Galaxy S20",
    description: "Hiệu năng cao, phù hợp testing đa nhiệm",
    available: 12,
    sold: "340",
    price: "45.000đ/ngày",
    rating: 4.8,
    specs: {
      resolution: "1440×3200",
      cpu: "Exynos 990",
      ram: "8GB RAM",
      storage: "128GB",
      android: "Android 11",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "96%",
  },
  {
    id: 13,
    name: "Galaxy S21",
    description: "Thiết bị mới hơn, phù hợp kiểm thử app hiện đại",
    available: 8,
    sold: "410",
    price: "55.000đ/ngày",
    rating: 4.9,
    specs: {
      resolution: "1440×3200",
      cpu: "Exynos 2100",
      ram: "8GB RAM",
      storage: "128GB",
      android: "Android 11",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "98%",
  },
  {
    id: 14,
    name: "Galaxy S22",
    description: "Hiệu năng tốt, camera ổn, phù hợp demo",
    available: 5,
    sold: "180",
    price: "65.000đ/ngày",
    rating: 4.9,
    specs: {
      resolution: "1440×3088",
      cpu: "Exynos 2200",
      ram: "8GB RAM",
      storage: "128GB",
      android: "Android 12",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "99%",
  },
  {
    id: 15,
    name: "Galaxy S23",
    description: "Thiết bị top-tier cho các kịch bản nặng",
    available: 3,
    sold: "90",
    price: "85.000đ/ngày",
    rating: 5.0,
    specs: {
      resolution: "2340×1080",
      cpu: "Snapdragon/Exynos",
      ram: "8GB RAM",
      storage: "256GB",
      android: "Android 13",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "99%",
  },
  {
    id: 16,
    name: "Pixel 3",
    description: "Thiết bị Google, phù hợp test Android gốc",
    available: 14,
    sold: "60",
    price: "20.000đ/ngày",
    rating: 4.2,
    specs: {
      resolution: "1080×2160",
      cpu: "Snapdragon 845",
      ram: "4GB RAM",
      storage: "64GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "50%",
  },
  {
    id: 17,
    name: "Pixel 4",
    description: "Test Android gốc, camera thử nghiệm",
    available: 6,
    sold: "30",
    price: "25.000đ/ngày",
    rating: 4.3,
    specs: {
      resolution: "1080×2280",
      cpu: "Snapdragon 855",
      ram: "6GB RAM",
      storage: "64GB",
      android: "Android 11",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "60%",
  },
  {
    id: 18,
    name: "Xiaomi Redmi Note 9",
    description: "Giá rẻ, phù hợp load test nhẹ",
    available: 120,
    sold: "500",
    price: "9.000đ/ngày",
    rating: 4.0,
    specs: {
      resolution: "1080×2340",
      cpu: "MediaTek",
      ram: "4GB RAM",
      storage: "64GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "40%",
  },
  {
    id: 19,
    name: "Xiaomi Mi 11",
    description: "Hiệu năng cao, phù hợp automation nặng",
    available: 9,
    sold: "75",
    price: "40.000đ/ngày",
    rating: 4.7,
    specs: {
      resolution: "1440×3200",
      cpu: "Snapdragon 888",
      ram: "8GB RAM",
      storage: "128GB",
      android: "Android 11",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "85%",
  },
  {
    id: 20,
    name: "Galaxy A50",
    description: "Cân bằng cho testing hằng ngày",
    available: 60,
    sold: "320",
    price: "16.000đ/ngày",
    rating: 4.4,
    specs: {
      resolution: "1080×2340",
      cpu: "Exynos",
      ram: "4GB RAM",
      storage: "128GB",
      android: "Android 10",
      rooted: "Not Rooted",
    },
    image: "https://s3.onox.pro/dev/static/samsung-galaxy-a6-2018-.jpg",
    sale: "78%",
  },
];

export const tabs = [
  { id: "custom", label: "Custom Proxy", active: true },
  { id: "dynamic", label: "Dynamic Proxy", active: false },
  { id: "resources", label: "More Resources", active: false },
];
export const apps = [
  {
    id: 1,
    name: "Facebook I...",
    version: "517.0.0.70.92",
    icon: imgApp,
  },
  {
    id: 2,
    name: "Facebook I...",
    version: "517.0.0.70.92",
    icon: imgApp,
  },
  {
    id: 3,
    name: "Facebook I...",
    version: "517.0.0.70.92",
    icon: imgApp,
  },
  {
    id: 4,
    name: "Facebook I...",
    version: "517.0.0.70.92",
    icon: imgApp,
  },
];
export const accessToken = "accessToken";

export const AUDIO_CODECS = ["off", "raw", "aac", "opus"];

export const VIDEO_CODECS = ["off", "h264-tiny", "h264-webcodec"];

export const DEAULT_MAX_FPS = 60;

export const DEAULT_BIT_RATE = 4;

export const FILE_EXTENSIONS = ["apk", "apkm", "xapk"];

export const PACK_OPTIONS = {
  useRecords: true,
  structuredClone: true,
  bundleStrings: true,
};
export const MOUSE_EVENT_BUTTON_TO_ANDROID_BUTTON = [
  AndroidMotionEventButton.Primary,
  AndroidMotionEventButton.Tertiary,
  AndroidMotionEventButton.Secondary,
  AndroidMotionEventButton.Back,
  AndroidMotionEventButton.Forward,
];
